name: Build dtbo.img from ZIP

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL ZIP berisi file .dtbo"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget curl

      - name: Download ZIP (support MediaFire)
        run: |
          echo "Downloading from: ${{ github.event.inputs.zip_url }}"
          wget --content-disposition "${{ github.event.inputs.zip_url }}" -O dtbo.zip

      - name: Check file
        run: |
          file dtbo.zip
          ls -lah dtbo.zip

      - name: Extract ZIP
        run: |
          mkdir extracted
          unzip -o dtbo.zip -d extracted

      - name: Find DTBO files
        run: |
          find extracted -type f -name "*.dtbo" | sort > list.txt
          cat list.txt

          if [ ! -s list.txt ]; then
            echo "❌ No dtbo files found!"
            exit 1
          fi

      - name: Download mkdtboimg
        run: |
          curl -L "https://android.googlesource.com/platform/system/libufdt/+/refs/heads/main/utils/src/mkdtboimg.py?format=TEXT" | base64 -d > mkdtboimg.py
          chmod +x mkdtboimg.py

      - name: Build dtbo.img
        run: |
          python3 mkdtboimg.py create dtbo.img $(cat list.txt)

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: dtbo-image
          path: dtbo.img