name: Extract Kernel Modules

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Find and Copy kernel_modules
        run: |
          mkdir -p output

          if [ -d "drivers/misc/device_info" ]; then
            cp -r drivers/misc/device_info output/
          fi
          
          

      - name: Zip result
        run: |
          cd output
            zip -r device_info.zip device_info

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel_modules
          path: output/*.zip
