name: SukiSU Integration Only

on:
  push:
    branches:
      - 4.14.200-KernelSU
  workflow_dispatch:
  

jobs:
  integrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 4.14.200-KernelSU
        fetch-depth: 0

    - name: Configure Git identity
      run: |
        git config --local user.name "Aflahal"
        git config --local user.email "zxx97607@gmail.com"

    - name: Run SukiSU Setup
      run: |
        curl -LSs "https://raw.githubusercontent.com/backslashxx/KernelSU/master/kernel/setup.sh" | bash
        git rm -r --cached KernelSU || true
        find KernelSU -name ".git" -exec rm -rf {} + || true


    - name: Commit and Push
      run: |
        git add .
        
        if git diff --cached --quiet; then
          echo "No changes detected."
        else
          git commit -m "kernel: import KernelSU source"
          git push origin 4.14.200-KernelSU
        fi
